import type {Comparison,RemainingMetric} from './incident-types';

export function RemainingTravel({label,metric}:{label:string;metric:RemainingMetric}){
  return <div className="if-metric"><b>{label}</b>{metric.comparable&&metric.base!==null&&metric.candidate!==null?<><span>{metric.base} → {metric.candidate}{metric.delta&&` (${metric.delta})`}</span><small>{metric.baseline}</small></>:<><span className="if-unavailable">Unavailable</span><small>{metric.reason??'Comparable remaining-travel data was not supplied.'}</small></>}</div>;
}
export default function ComparisonDetails({comparison,onOrder}:{comparison:Comparison;onOrder:(id:string)=>void}){
  return <div className="if-comparison-details"><div className="if-comparison-context"><span>BASE VS SINGLE CANDIDATE</span><b>{comparison.basePlanId} → {comparison.candidatePlanId}</b><small>{comparison.businessDate} · Comparison snapshot {comparison.comparisonTime}</small></div><div className="if-comparison-grid">
    <section><h3>Assignment Changes</h3>{comparison.assignmentChanges.map(change=><button className="if-change-row" key={change.orderId} onClick={()=>onOrder(change.orderId)}><b>{change.orderId}</b><span>{change.baseVehicle??'Unassigned'} → {change.candidateVehicle??'Unassigned'}</span><em>{change.change}</em><small>{change.baseState} → {change.candidateState} · {change.reason}</small></button>)}<p className="if-comparison-note">{comparison.unassignedChanges.length===0?'No assigned / unassigned state changes.':comparison.unassignedChanges.map(change=>`${change.orderId}: ${change.from} → ${change.to}. ${change.reason}`).join(' ')}</p></section>
    <section><h3>Route Task Changes</h3>{comparison.stopChanges.map((change,i)=><div className="if-task-change" key={`${change.action}-${change.vehicle}-${i}`}><span>{change.change} · {change.action}</span><b>{change.vehicle} · {change.orders.join(', ')}</b><small>{change.location}. {change.reason}</small></div>)}</section>
    <section><h3>ETA Changes</h3>{comparison.etaChanges.map(change=><button className="if-change-row" key={change.orderId} onClick={()=>onOrder(change.orderId)}><b>{change.orderId}</b>{change.unavailableReason?<><span>Unavailable</span><small>{change.unavailableReason}</small></>:<><span>{change.oldEta??'Unavailable'} → {change.newEta??'Unavailable'}</span><em>{change.delta??'Delta unavailable'}</em><small>Baseline: {change.baseline}</small></>}</button>)}</section>
    <section><h3>Plan Disturbance</h3><dl className="if-disturbance"><div><dt>Orders reassigned</dt><dd>{comparison.disturbanceSummary.reassignedOrders}</dd></div><div><dt>Affected vehicles</dt><dd>{comparison.disturbanceSummary.affectedVehicles}</dd></div><div><dt>Route tasks changed</dt><dd>{comparison.disturbanceSummary.routeTasksChanged}</dd></div></dl><p className="if-comparison-note">{comparison.disturbanceSummary.routeSummary}</p><p className="if-protected-note">{comparison.disturbanceSummary.protectedWork}</p><h3>Remaining Travel</h3><RemainingTravel label="Remaining distance" metric={comparison.remainingMetrics.distance}/><RemainingTravel label="Remaining duration" metric={comparison.remainingMetrics.duration}/><h3>Missing Metrics</h3>{comparison.missingMetrics.length===0?<p className="if-comparison-note">No missing metrics reported.</p>:comparison.missingMetrics.map(metric=><p className="if-comparison-note" key={metric.metric}><b>{metric.metric}:</b> {metric.reason}</p>)}</section>
  </div></div>;
}

