"use client";
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,Check,ChevronDown,Clock3,Map,Package,RefreshCw,Route as RouteIcon,ShieldCheck,Sparkles,Truck,Users,Waypoints} from 'lucide-react';
import OperationsMap from './operations-map';
import {demoOperationsAdapter} from './operations-data';
import type {OperationsSnapshot,Route} from './operations-data';

type Tab='planning'|'live';
type Props={active:boolean;onOpenIncident:(id:string)=>void;recoveryRevision:number};
const display=(value:number)=>new Intl.NumberFormat('en-SG').format(value);

function Metric({label,value,note,icon:Icon,tone='gold'}:{label:string;value:string|number;note:string;icon:typeof Package;tone?:string}){
  return <article className="ops-metric"><span className={`ops-metric-icon ${tone}`}><Icon/></span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>;
}
function SectionTitle({eyebrow,title,detail,action}:{eyebrow:string;title:string;detail?:string;action?:React.ReactNode}){
  return <div className="ops-section-heading"><div><span>{eyebrow}</span><h2>{title}</h2>{detail&&<p>{detail}</p>}</div>{action}</div>;
}
function StatusPill({value,tone}:{value:string;tone:'green'|'amber'|'red'|'muted'}){return <span className={`ops-status ${tone}`}><i/>{value.replaceAll('_',' ')}</span>;}
function RouteSequence({route}:{route:Route}){return <div className="ops-stop-sequence">{route.stops.map((stop,index)=><div className="ops-sequence-step" key={stop.id}><span className={`ops-step-dot ${stop.kind.toLowerCase()}`}>{index+1}</span><div><b>{stop.kind} · {stop.order}</b><small>{stop.place}</small></div><time>{stop.at}</time></div>)}</div>;}

export default function OperationsPage({active:pageActive,onOpenIncident,recoveryRevision}:Props){
  const [snapshot,setSnapshot]=useState<OperationsSnapshot|null>(null),[tab,setTab]=useState<Tab>('planning'),[view,setView]=useState<'map'|'timeline'>('map');
  const [phase,setPhase]=useState<'READY'|'SOLVING'|'PLAN_READY'|'CURRENT'|'ERROR'>('READY'),[message,setMessage]=useState<string|null>(null);
  const [selectedRoute,setSelectedRoute]=useState<string|null>(null),[expandedRoute,setExpandedRoute]=useState<string|null>(null),[busy,setBusy]=useState(false);
  useEffect(()=>{let live=true;void demoOperationsAdapter.load().then(data=>{if(live){setSnapshot(data);setPhase(data.plan?.status==='CURRENT'?'CURRENT':data.plan?'PLAN_READY':'READY');}});return()=>{live=false;};},[]);
  const chosen=snapshot?.routes.find(route=>route.id===selectedRoute)??null;
  const active=snapshot?.plan?.status==='CURRENT';
  const riskOrders=snapshot?.routes.flatMap(route=>route.stops.filter(stop=>stop.kind==='DELIVERY'&&stop.risk==='AT_RISK'))??[];
  const uniqueOrders=new Set(snapshot?.routes.flatMap(route=>route.stops.map(stop=>stop.order))??[]);
  const selectRoute=(id:string)=>{setSelectedRoute(id);setExpandedRoute(id);};
  async function generate(){if(!snapshot||busy)return;setBusy(true);setPhase('SOLVING');setMessage(null);try{const next=await demoOperationsAdapter.generate(snapshot);setSnapshot(next);setPhase('PLAN_READY');setSelectedRoute(next.routes[0]?.id??null);}catch(error){setPhase('ERROR');setMessage(error instanceof Error?error.message:'Plan generation failed.');}finally{setBusy(false);}}
  async function confirm(){if(!snapshot||busy)return;setBusy(true);setMessage(null);try{const next=await demoOperationsAdapter.confirm(snapshot);setSnapshot(next);setPhase('CURRENT');setTab('live');}catch(error){setPhase('ERROR');setMessage(error instanceof Error?error.message:'Could not confirm plan.');}finally{setBusy(false);}}
  const brief=useMemo(()=>snapshot?[`${riskOrders.length} delivery tasks are marked AT_RISK in this demo snapshot.`,`${snapshot.alerts.filter(item=>item.level==='incident').length} incident awaits recovery review.`,`Positions on the map are simulated and do not determine ETA or risk.`]:[],[snapshot,riskOrders.length]);
  if(!snapshot)return <div className="ops-page ops-loading" role="status">Loading Operations workspace…</div>;
  return <div className="ops-page">
    <header className="ops-header"><div><div className="ops-breadcrumb">NEXUS / OPERATIONS <span>· FRONTEND DEMO DATA</span></div><h1>Operations</h1><p>Plan the day. See every route in motion.</p></div><div className="ops-header-state"><span className="ops-live-dot"/>SINGAPORE NETWORK<small>{snapshot.businessDate}</small></div></header>
    <nav className="ops-tabs" aria-label="Operations views"><button className={tab==='planning'?'active':''} aria-current={tab==='planning'?'page':undefined} onClick={()=>setTab('planning')}><RouteIcon/>Planning</button><button className={tab==='live'?'active':''} aria-current={tab==='live'?'page':undefined} onClick={()=>setTab('live')}><Waypoints/>Live Execution</button><div className="ops-tab-plan">{snapshot.plan?<><span>{snapshot.plan.id} · V{snapshot.plan.version}</span><StatusPill value={snapshot.plan.status} tone={active?'green':'amber'}/></>:<span>No current plan</span>}</div></nav>
    {tab==='planning'?<div className="ops-body">
      <section className="ops-card ops-readiness"><SectionTitle eyebrow="01 / PLANNING READINESS" title="Ready for dispatch" detail="Resources and constraints for the demo business day."/><div className="ops-readiness-grid">
        <Metric label="Orders to plan" value={snapshot.readiness.orders} note="Daily order pool" icon={Package}/>
        <Metric label="Merchants ready" value={snapshot.readiness.merchantsReady} note={`${snapshot.readiness.merchantsPreparing} preparing · ${snapshot.readiness.merchantsDelayed} delayed`} icon={Check} tone="green"/>
        <Metric label="Vehicles available" value={snapshot.readiness.vehicles} note="Assigned fleet" icon={Truck}/>
        <Metric label="Drivers available" value={snapshot.readiness.drivers} note="Capacity aligned" icon={Users}/>
      </div></section>
      <div className="ops-planning-grid"><section className="ops-card ops-inputs"><SectionTitle eyebrow="02 / INPUTS" title="Planning inputs" detail="Business constraints represented in the planning fixture."/>
        <div className="ops-input-list"><div><Clock3/><span><b>Delivery time windows</b><small>Order-specific arrival windows</small></span><em>Applied</em></div><div><Check/><span><b>Merchant ready time</b><small>Pickup after merchant readiness</small></span><em>Applied</em></div><div><Package/><span><b>Pickup & delivery service</b><small>Stop duration included in sequence</small></span><em>Applied</em></div><div><Truck/><span><b>Vehicle demand & capacity</b><small>Assigned load within vehicle limit</small></span><em>Applied</em></div></div>
        <div className="ops-constraint"><span>CONSTRAINT SUMMARY</span><p>{snapshot.constraintSummary.join(' · ')}</p></div>
        <div className="ops-plan-action"><div><span className={`ops-phase ops-phase-${phase.toLowerCase()}`}>{phase.replaceAll('_',' ')}</span><small>{phase==='SOLVING'?'Checking orders, capacity and time windows…':phase==='PLAN_READY'?'Review assignments before confirming.':phase==='CURRENT'?'Confirmed plan is available in Live Execution.':'Normal planning uses Workflow + OR-Tools.'}</small></div><button onClick={()=>void generate()} disabled={busy||phase==='CURRENT'}>{busy&&phase==='SOLVING'?<RefreshCw className="spin"/>:<RouteIcon/>}{phase==='CURRENT'?'Plan current':phase==='PLAN_READY'?'Regenerate plan':'Generate plan'}</button></div>
        {message&&<p className="ops-message" role="alert">{message}</p>}
      </section><section className="ops-card ops-planning-map"><SectionTitle eyebrow="03 / NETWORK" title="Singapore planning map" detail="Merchant pickups, delivery stops and planned routes."/><OperationsMap active={pageActive} snapshot={snapshot} mode="planning" selectedRoute={selectedRoute} onSelectRoute={selectRoute} onOpenIncident={onOpenIncident}/></section></div>
      <section className="ops-card ops-review"><SectionTitle eyebrow="04 / PLAN REVIEW" title={snapshot.plan?`Plan V${snapshot.plan.version} · ${snapshot.plan.status==='CURRENT'?'Current':'Ready for review'}`:'Plan preview'} detail={snapshot.plan?'Review route assignments and stop order before execution.':'Generate a plan to review vehicle assignments.'} action={snapshot.plan?.status==='DRAFT'?<button className="ops-primary" onClick={()=>void confirm()} disabled={busy}><Check/> {busy?'Confirming…':'Confirm plan'}</button>:snapshot.plan?.status==='CURRENT'?<button className="ops-primary" onClick={()=>setTab('live')}>Continue to Live Execution <ArrowRight/></button>:undefined}/>
        {snapshot.plan?<><div className="ops-review-summary"><span><b>{snapshot.routes.length}</b> Routes</span><span><b>{uniqueOrders.size}</b> Assigned orders in preview</span><span><b>{snapshot.unassigned.length}</b> Unassigned in preview</span><span><b>{display(snapshot.routes.reduce((sum,route)=>sum+route.distanceKm,0))} km</b> Planned distance</span></div><div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Vehicle / Driver</th><th>Assigned orders</th><th>Stops</th><th>Distance</th><th>Duration</th><th>Utilization</th><th></th></tr></thead><tbody>{snapshot.routes.map(route=><tr key={route.id} className={expandedRoute===route.id?'selected':''}><td><button className="ops-table-link" onClick={()=>selectRoute(route.id)}>{route.vehicle}<small>{route.driver} · {route.id}</small></button></td><td>{route.stops.filter(stop=>stop.kind==='DELIVERY').map(stop=>stop.order).join(' · ')}</td><td>{route.stops.length}</td><td>{route.distanceKm.toFixed(1)} km</td><td>{route.durationMin} min</td><td>{route.utilization}%</td><td><button className="ops-icon-button" aria-label={`Show ${route.vehicle} stop sequence`} aria-expanded={expandedRoute===route.id} onClick={()=>setExpandedRoute(current=>current===route.id?null:route.id)}><ChevronDown/></button></td></tr>)}</tbody></table></div>{expandedRoute&&<div className="ops-review-detail"><b>{snapshot.routes.find(route=>route.id===expandedRoute)?.vehicle} · Pickup → Delivery sequence</b>{snapshot.routes.find(route=>route.id===expandedRoute)&&<RouteSequence route={snapshot.routes.find(route=>route.id===expandedRoute)!}/>}</div>}{snapshot.unassigned.length>0&&<div className="ops-unassigned">Unassigned: {snapshot.unassigned.map(item=>`${item.order} (${item.reason})`).join(', ')}</div>}</>:<div className="ops-empty"><RouteIcon/><span>No generated plan yet.</span></div>}
      </section>
    </div>:<div className="ops-body">
      {!active?<section className="ops-card ops-no-plan"><RouteIcon/><div><h2>No Current Plan to execute</h2><p>{message??(recoveryRevision>0?'Recovery was applied in the Incident demo. Updated route and stop data are unavailable here; generate a new demo plan to continue.':'Generate, review and confirm a plan in Planning before monitoring execution.')}</p></div><button className="ops-primary" onClick={()=>setTab('planning')}>Open Planning <ArrowRight/></button></section>:<>
        <div className="ops-current-strip"><div><span className="ops-live-dot"/><b>CURRENT PLAN V{snapshot.plan!.version}</b><small>{snapshot.plan!.id} · {snapshot.businessDate}</small></div><span>DEMO OPERATIONS · SIMULATED POSITIONS</span></div>
        <div className="ops-live-metrics"><Metric label="Assigned orders" value={uniqueOrders.size} note="In this route preview" icon={Package}/><Metric label="Active vehicles" value={snapshot.routes.filter(route=>route.status!=='UNAVAILABLE').length} note={`${snapshot.routes.length} routes planned`} icon={Truck} tone="green"/><Metric label="On-time rate" value="—" note="Not provided by fixture" icon={Clock3}/><Metric label="At-risk deliveries" value={riskOrders.length} note="Risk status, not incidents" icon={AlertTriangle} tone="amber"/></div>
        <div className="ops-live-grid"><section className="ops-card ops-live-stage"><SectionTitle eyebrow="01 / LIVE EXECUTION" title={view==='map'?'Live operations map':'Vehicle task timeline'} detail={view==='map'?'Simulated vehicle movement over the confirmed plan.':'Planned sequence, execution and risk shown separately.'} action={<div className="ops-view-switch"><button className={view==='map'?'active':''} aria-pressed={view==='map'} onClick={()=>setView('map')}><Map/> Map</button><button className={view==='timeline'?'active':''} aria-pressed={view==='timeline'} onClick={()=>setView('timeline')}><Clock3/> Task Timeline</button></div>}/>
          {view==='map'?<OperationsMap active={pageActive} snapshot={snapshot} mode="live" selectedRoute={selectedRoute} onSelectRoute={selectRoute} onOpenIncident={onOpenIncident}/>:<div className="ops-timeline">{snapshot.routes.map(route=><article key={route.id} className={selectedRoute===route.id?'selected':''}><button onClick={()=>selectRoute(route.id)}><Truck/><b>{route.vehicle}</b><small>{route.driver}</small><StatusPill value={route.status} tone={route.status==='UNAVAILABLE'?'red':route.status==='AT_RISK'?'amber':'green'}/></button><div className="ops-timeline-stops">{route.stops.map(stop=><div key={stop.id} className={stop.risk==='AT_RISK'?'risk':''}><span>{stop.at}</span><b>{stop.kind} · {stop.order}</b><small>{stop.place}</small><em>{stop.execution.replaceAll('_',' ')} · {stop.risk.replaceAll('_',' ')}</em></div>)}</div></article>)}</div>}
          {chosen&&<div className="ops-selected-route"><span>{chosen.vehicle} / {chosen.id}</span><b>{chosen.stops.filter(stop=>stop.execution==='IN_PROGRESS')[0]?.kind??'Next task'} · {chosen.stops.filter(stop=>stop.execution==='IN_PROGRESS')[0]?.order??'—'}</b><small>Planned route · {chosen.distanceKm.toFixed(1)} km · {chosen.durationMin} min</small><button onClick={()=>setSelectedRoute(null)}>Clear selection</button></div>}
        </section><aside className="ops-card ops-brief"><SectionTitle eyebrow="FACT-BASED BRIEF" title="AI Operations Brief" detail="Summary of the demo snapshot, not a planning decision."/><div className="ops-brief-emblem"><Sparkles/><span>NETWORK PULSE</span><b>{riskOrders.length} tasks need attention</b></div><ul>{brief.map(line=><li key={line}><span/> {line}</li>)}</ul><div className="ops-brief-footer"><ShieldCheck/> Recovery decisions remain in Incidents.</div></aside></div>
        <div className="ops-lower-grid"><section className="ops-card"><SectionTitle eyebrow="02 / FLEET" title="Active riders / vehicles" detail="Execution and risk are separate dimensions."/><div className="ops-vehicle-list">{snapshot.routes.map(route=><button key={route.id} className={selectedRoute===route.id?'selected':''} onClick={()=>selectRoute(route.id)}><span className="ops-vehicle-icon"><Truck/></span><span><b>{route.vehicle}</b><small>{route.driver} · {route.id}</small></span><StatusPill value={route.status} tone={route.status==='UNAVAILABLE'?'red':route.status==='AT_RISK'?'amber':'green'}/><ArrowRight/></button>)}</div></section>
          <section className="ops-card"><SectionTitle eyebrow="03 / SIGNALS" title="Active alerts" detail="AT_RISK remains separate from an incident."/><div className="ops-alert-list">{snapshot.alerts.map(alert=><article key={alert.id} className={alert.level}><AlertTriangle/><div><b>{alert.title}</b><small>{alert.detail}</small><span>{alert.level==='incident'?`INCIDENT · ${alert.incidentId}`:'AT_RISK · ALERT ONLY'}</span></div>{alert.incidentId&&<button onClick={()=>onOpenIncident(alert.incidentId!)}>Resolve in Incidents <ArrowRight/></button>}</article>)}</div></section>
          <section className="ops-card"><SectionTitle eyebrow="04 / DISPATCH" title="Live route queue" detail="Current stop and remaining route tasks."/><div className="ops-queue">{snapshot.routes.map(route=><button key={route.id} onClick={()=>{selectRoute(route.id);setView('timeline');}}><span><b>{route.id}</b><small>{route.vehicle}</small></span><span><b>{route.stops.filter(stop=>stop.execution==='COMPLETED').length}/{route.stops.length}</b><small>stops completed</small></span><StatusPill value={route.status} tone={route.status==='UNAVAILABLE'?'red':route.status==='AT_RISK'?'amber':'green'}/><ArrowRight/></button>)}</div></section></div>
      </>}
    </div>}
    <footer className="ops-footer">NEXUS / OPERATIONS <span>Real Singapore basemap · Frontend demo operations data · Simulated vehicle movement</span></footer>
  </div>;
}
