import assert from 'node:assert/strict';
import {renderToStaticMarkup} from 'react-dom/server';
import IncidentFocusPage from '../app/incidents/incident-focus-page';
import {incidentWorkspace} from '../app/incidents/incident-mock';
import {mockIncidentGateway} from '../app/incidents/incident-gateway';
import {canApproveCandidate} from '../app/incidents/incident-types';
import {incidentFocusBounds,incidentOverlayData} from '../app/incidents/incident-map-data';

const original=structuredClone(incidentWorkspace);
assert.ok(canApproveCandidate(original));
const stale=structuredClone(original);
stale.candidatePlan.status='STALE';stale.comparison.candidateStatus='STALE';stale.comparison.baseIsCurrent=false;stale.comparison.approvalEligible=false;
stale.comparison.staleReason='Base plan has changed since candidate generation.';
assert.ok(stale.comparison.comparable);
assert.equal(canApproveCandidate(stale),false);
await assert.rejects(()=>mockIncidentGateway.approve(stale),/Base plan has changed/);
const blockedMarkup=renderToStaticMarkup(<IncidentFocusPage data={stale} active={false}/>);
assert.match(blockedMarkup,/Comparable/);assert.match(blockedMarkup,/Not eligible/);assert.match(blockedMarkup,/Base plan has changed/);
assert.match(blockedMarkup,/<button class="if-approve" disabled=""[^>]*>/);
const notEligible=structuredClone(original);notEligible.comparison.approvalEligible=false;
assert.equal(canApproveCandidate(notEligible),false);
await assert.rejects(()=>mockIncidentGateway.approve(notEligible));
await assert.rejects(()=>mockIncidentGateway.reject(original,'   '),/reason/);
const rejected=await mockIncidentGateway.reject(original,'Handover access needs review');
assert.equal(rejected.candidatePlan.status,'REJECTED');assert.equal(canApproveCandidate(rejected),false);
const request={preserveCompletedWork:true,recoveryVehicles:'KEEP_PROPOSED',maxAdditionalDelayMinutes:12} as const;
const revised=await mockIncidentGateway.modify(rejected,request);
assert.equal(revised.candidatePlan.revision,2);assert.notEqual(revised.candidatePlan.id,original.candidatePlan.id);
assert.equal(revised.comparison.candidatePlanId,revised.candidatePlan.id);assert.ok(canApproveCandidate(revised));
assert.deepEqual(revised,await mockIncidentGateway.modify(rejected,request),'Mock replan is deterministic');
assert.deepEqual(revised.completedStops,original.completedStops);
assert.equal(original.candidatePlan.status,'READY','Original fixture remains unchanged');
const applied=await mockIncidentGateway.approve(revised);
assert.equal(applied.candidatePlan.status,'APPLIED');assert.equal(canApproveCandidate(applied),false);
await assert.rejects(()=>mockIncidentGateway.approve(applied));
await assert.rejects(()=>mockIncidentGateway.reject(applied,'Too late'));
assert.equal(original.comparison.remainingMetrics.distance.base,null);
assert.match(renderToStaticMarkup(<IncidentFocusPage data={original} active={false}/>),/Historical base-plan remaining-distance snapshot is unavailable/);
const changed=structuredClone(original);
changed.comparison.mapChanges.base={type:'LineString',coordinates:[[103.9,1.35],[103.91,1.36]]};
assert.deepEqual(incidentOverlayData(changed,true).features.find(f=>f.properties?.kind==='original')?.geometry,changed.comparison.mapChanges.base,'Changes Only uses supplied comparison geometry');
assert.ok(!incidentOverlayData(changed,true).features.some(f=>f.properties?.kind==='completed'));
for(const [id,lng,lat] of [['INC-012',103.944,1.354],['INC-018',103.786,1.437],['INC-025',103.846,1.3]] as const){
  const data=structuredClone(original);data.incident.id=id;data.incident.location={lng,lat};
  const bounds=incidentFocusBounds(data);
  assert.ok(Math.abs((bounds[0][0]+bounds[1][0])/2-lng)<1e-9);
  assert.ok(Math.abs((bounds[0][1]+bounds[1][1])/2-lat)<1e-9);
}
console.log('PASS: eligibility, stale comparison, reject, deterministic modify, protected work, approval, missing metrics, explicit comparison overlays and Singapore-wide camera inputs.');
